<?php

return [
    'India' => [
        'prefix' => 'IND',
        'timezones' => [
            'IST',
        ],
        'types' => [
            'Full-time',
            'Contract',
            'Contract-2-Hire',
        ],
        'states' => [
            'Andhra Pradesh' => 'IST',
            'Arunachal Pradesh' => 'IST',
            'Assam' => 'IST',
            'Bihar' => 'IST',
            'Chhattisgarh' => 'IST',
            'Delhi' => 'IST',
            'Goa' => 'IST',
            'Gujarat' => 'IST',
            'Haryana' => 'IST',
            'Himachal Pradesh' => 'IST',
            'Jharkhand' => 'IST',
            'Karnataka' => 'IST',
            'Kerala' => 'IST',
            'Madhya Pradesh' => 'IST',
            'Maharashtra' => 'IST',
            'Manipur' => 'IST',
            'Meghalaya' => 'IST',
            'Mizoram' => 'IST',
            'Nagaland' => 'IST',
            'Odisha' => 'IST',
            'Punjab' => 'IST',
            'Rajasthan' => 'IST',
            'Sikkim' => 'IST',
            'Tamil Nadu' => 'IST',
            'Telangana' => 'IST',
            'Tripura' => 'IST',
            'Uttar Pradesh' => 'IST',
            'Uttarakhand' => 'IST',
            'West Bengal' => 'IST',
        ],
        'currency' => [
            'INR'
        ]
    ],

    'United States' => [
        'prefix' => 'USA',
        'timezones' => [
            'EST',
            'CST',
            'MST',
            'PST',
        ],
        'types' => [
            'W2 Contract',
            'C2C Contract',
            'Full-Time',
            'W2/C2C Contract',
            'Contract-2-Hire',
        ],
        'states' => [
            'Alabama' => 'CST',
            'Alaska' => 'AKT',
            'Arizona' => 'MST',
            'Arkansas' => 'CST',
            'California' => 'PST',
            'Colorado' => 'MST',
            'Connecticut' => 'EST',
            'Delaware' => 'EST',
            'Florida' => 'EST',
            'Georgia' => 'EST',
            'Hawaii' => 'HST',
            'Idaho' => 'MST',
            'Illinois' => 'CST',
            'Indiana' => 'EST',
            'Iowa' => 'CST',
            'Kansas' => 'CST',
            'Kentucky' => 'EST',
            'Louisiana' => 'CST',
            'Maine' => 'EST',
            'Maryland' => 'EST',
            'Massachusetts' => 'EST',
            'Michigan' => 'EST',
            'Minnesota' => 'CST',
            'Mississippi' => 'CST',
            'Missouri' => 'CST',
            'Montana' => 'MST',
            'Nebraska' => 'CST',
            'Nevada' => 'PST',
            'New Hampshire' => 'EST',
            'New Jersey' => 'EST',
            'New Mexico' => 'MST',
            'New York' => 'EST',
            'North Carolina' => 'EST',
            'North Dakota' => 'CST',
            'Ohio' => 'EST',
            'Oklahoma' => 'CST',
            'Oregon' => 'PST',
            'Pennsylvania' => 'EST',
            'Rhode Island' => 'EST',
            'South Carolina' => 'EST',
            'South Dakota' => 'CST',
            'Tennessee' => 'CST',
            'Texas' => 'CST',
            'Utah' => 'MST',
            'Vermont' => 'EST',
            'Virginia' => 'EST',
            'Washington' => 'PST',
            'West Virginia' => 'EST',
            'Wisconsin' => 'CST',
            'Wyoming' => 'MST',
            'Washington DC' => 'EST',
        ],
        'currency' => [
            'USD'
        ]
    ],

    'Canada' => [
        'prefix' => 'CAD',
        'timezones' => [
            'EST',
            'CST',
            'MST',
            'PST',
            'Any',
        ],
        'types' => [
            'Full-Time',
            'C2C Contract',
            'T4 Contract',
            'Contract-2-Hire',
            'C2C/T4 Contract',
        ],
        'states' => [
            'Alberta' => 'MST',
            'British Columbia' => 'PST',
            'Manitoba' => 'CST',
            'New Brunswick' => 'EST',
            'Newfoundland and Labrador' => 'EST',
            'Northwest Territories' => 'MST',
            'Nova Scotia' => 'AST',
            'Nunavut' => 'EST',
            'Ontario' => 'EST',
            'Prince Edward Island' => 'AST',
            'Quebec' => 'EST',
            'Saskatchewan' => 'CST',
            'Yukon' => 'PST',
        ],
        'currency' => [
            'CAD'
        ]
    ],
    'Mexico' => [
        'prefix' => 'MEX',
        'timezones' => [
            'CST',
            'MST',
            'PST',
            'EST',
        ],
        'types' => [
            'Full-Time',
            'Contract',
            'Contract-2-Hire',
        ],
        'states' => [
            'Aguascalientes' => 'CST',
            'Baja California' => 'PST',
            'Baja California Sur' => 'MST',
            'Campeche' => 'CST',
            'Chiapas' => 'CST',
            'Chihuahua' => 'MST',
            'Coahuila' => 'CST',
            'Colima' => 'CST',
            'Durango' => 'CST',
            'Guanajuato' => 'CST',
            'Guerrero' => 'CST',
            'Hidalgo' => 'CST',
            'Jalisco' => 'CST',
            'Mexico City' => 'CST',
            'Mexico State' => 'CST',
            'Michoacán' => 'CST',
            'Morelos' => 'CST',
            'Nayarit' => 'CST',
            'Nuevo León' => 'CST',
            'Oaxaca' => 'CST',
            'Puebla' => 'CST',
            'Querétaro' => 'CST',
            'Quintana Roo' => 'EST',
            'San Luis Potosí' => 'CST',
            'Sinaloa' => 'MST',
            'Sonora' => 'MST',
            'Tabasco' => 'CST',
            'Tamaulipas' => 'CST',
            'Tlaxcala' => 'CST',
            'Veracruz' => 'CST',
            'Yucatán' => 'CST',
            'Zacatecas' => 'CST',
        ],
        'currency' => [
            'MXN'
        ]
    ],
];
